### ISSUE TITLE
Fix for link dictionaries

### ISSUE THREAD

**Issue by bmomjian** [resurrecting-open-source-projects/txt2html#1]
Thanks for getting this project active again.  

I have used custom link dictionaries for years, but this feature has also been broken for years.  Here is a report of the problem I posted in 2019,, and a fix for it from 2011, [https://rt.cpan.org/Public/Bug/Display.html?id=130421](url).    Here is the fix patch:
[link-dict-fix.diff.txt](https://github.com/resurrecting-open-source-projects/txt2html/files/7808605/link-dict-fix.diff.txt)

**Comment by eribertomota** [comment]
Thanks @bmomjian. I already tested this change and I will commit it now.

**Comment by bmomjian** [comment]
Great, glad this is being fixed.
